import { Injectable } from "@nestjs/common";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentEvent, AgentRun } from "@agenthub/shared";
import type { PreparedWorktree } from "./worktree.service";

export interface RunnerContext {
  run: AgentRun;
  prompt: string;
  worktree: PreparedWorktree;
  emit: (event: Omit<AgentEvent, "eventId" | "seq" | "ts">) => void;
}

export interface RunnerResult {
  output: string;
  summary: string;
}

const AGENT_COMMAND_ENV_ALLOWLIST = [
  "PATH",
  "Path",
  "PATHEXT",
  "SystemRoot",
  "WINDIR",
  "TEMP",
  "TMP",
  "HOME",
  "USERPROFILE",
  "APPDATA",
  "LOCALAPPDATA",
  "ComSpec",
  "PSModulePath",
  "CLAUDE_CONFIG_DIR"
] as const;

export function buildAgentCommandEnv(source: NodeJS.ProcessEnv = process.env): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const key of AGENT_COMMAND_ENV_ALLOWLIST) {
    const value = source[key];
    if (value !== undefined) {
      env[key] = value;
    }
  }
  return env;
}

export function buildTodolistEngineeringPrompt(userPrompt: string): string {
  return [
    "你是 AgentHub 调用的本地 Claude CLI 编码代理。请只在当前工作目录这个目标 git worktree 内修改文件。",
    "",
    "用户原始需求：",
    userPrompt,
    "",
    "请把该需求实现为一个完整可运行的 TypeScript 前后端分离 todolist 系统，要求：",
    "- 根目录使用 pnpm workspace，并提供可直接安装和运行的 package.json / pnpm-workspace.yaml。",
    "- frontend/ 使用 Vite + React + TypeScript。",
    "- backend/ 使用 Express + TypeScript。",
    "- 实现基础 Todo CRUD：创建、读取列表、更新完成状态或标题、删除。",
    "- 前端必须通过后端 HTTP API 完成数据读写，不使用纯前端假数据作为最终实现。",
    "- 提供 README，说明安装、开发启动、API 和项目结构。",
    "- 删除或替换当前目标 worktree 内旧的 mock、generated、sentinel、validation 残留内容，避免最终项目仍依赖这些占位实现。",
    "- 不要修改当前目标 worktree 之外的任何文件或目录。",
    "- 完成后确保目标项目文件是可提交状态。"
  ].join("\n");
}

export function parseClaudeStreamLine(line: string): string | undefined {
  const trimmed = line.trim();
  if (!trimmed) {
    return undefined;
  }

  try {
    const parsed = JSON.parse(trimmed) as {
      type?: string;
      text?: string;
      content?: Array<{ type?: string; text?: string }>;
      delta?: { text?: string };
    };
    if (typeof parsed.text === "string") {
      return parsed.text;
    }
    if (typeof parsed.delta?.text === "string") {
      return parsed.delta.text;
    }
    const textPart = parsed.content?.find((part) => part.type === "text" && typeof part.text === "string");
    return textPart?.text;
  } catch {
    return trimmed;
  }

  return undefined;
}

@Injectable()
export class AgentRunner {
  private readonly children = new Map<string, ChildProcessWithoutNullStreams>();

  async run(context: RunnerContext): Promise<RunnerResult> {
    if (process.env.MOCK_AGENT === "true") {
      return this.runMock(context);
    }
    return this.runClaude(context);
  }

  cancel(runId: string): boolean {
    const child = this.children.get(runId);
    if (!child) {
      return false;
    }
    child.kill("SIGTERM");
    this.children.delete(runId);
    return true;
  }

  private async runMock(context: RunnerContext): Promise<RunnerResult> {
    const wrappedPrompt = buildTodolistEngineeringPrompt(context.prompt);
    context.emit({
      type: "agent_thinking",
      runId: context.run.id,
      conversationId: context.run.conversationId,
      agentId: context.run.agentId,
      payload: { mode: "mock", mock: true }
    });

    const backendDir = join(context.worktree.worktreePath, "backend", "src", "generated");
    const frontendDir = join(context.worktree.worktreePath, "frontend", "src", "generated");
    await mkdir(backendDir, { recursive: true });
    await mkdir(frontendDir, { recursive: true });

    await writeFile(
      join(backendDir, "todo-service.ts"),
      [
        "export interface TodoItem {",
        "  id: string;",
        "  title: string;",
        "  done: boolean;",
        "}",
        "",
        "export function createTodo(title: string): TodoItem {",
        "  return { id: crypto.randomUUID(), title, done: false };",
        "}",
        ""
      ].join("\n"),
      "utf8"
    );
    await writeFile(
      join(frontendDir, "TodoList.tsx"),
      [
        "export function TodoList() {",
        "  return <section><h2>Mock Todo List</h2><p>Generated by AgentHub MOCK_AGENT.</p></section>;",
        "}",
        ""
      ].join("\n"),
      "utf8"
    );

    const output = `MOCK_AGENT=true mock run generated todo examples. Wrapped prompt:\n${wrappedPrompt}`;
    await writeFile(context.worktree.logPath, `${output}\n`, "utf8");
    context.emit({
      type: "text_delta",
      runId: context.run.id,
      conversationId: context.run.conversationId,
      agentId: context.run.agentId,
      payload: { text: output }
    });

    return {
      output,
      summary: `# AgentHub Run ${context.run.id}\n\n${output}\n`
    };
  }

  private async runClaude(context: RunnerContext): Promise<RunnerResult> {
    const wrappedPrompt = buildTodolistEngineeringPrompt(context.prompt);
    const command = process.env.AGENT_COMMAND ?? "claude";
    const args = ["--print", "--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"];
    const evidence = {
      mode: "claude-cli",
      command,
      cwd: context.worktree.worktreePath,
      shell: true
    };
    const evidenceLog = `Agent execution mode: ${JSON.stringify(evidence)}\n`;

    context.emit({
      type: "agent_thinking",
      runId: context.run.id,
      conversationId: context.run.conversationId,
      agentId: context.run.agentId,
      payload: evidence
    });
    await writeFile(context.worktree.logPath, evidenceLog, "utf8");

    return new Promise((resolve, reject) => {
      let child: ChildProcessWithoutNullStreams;
      try {
        child = spawn(command, args, {
          cwd: context.worktree.worktreePath,
          env: buildAgentCommandEnv(),
          shell: true
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        void writeFile(context.worktree.logPath, `${evidenceLog}Spawn failed: ${message}\n`, "utf8");
        reject(new Error(`Failed to spawn agent command "${command}": ${message}`));
        return;
      }
      this.children.set(context.run.id, child);
      let output = "";
      let stderr = "";
      let settled = false;

      child.stdout.on("data", (chunk: Buffer) => {
        for (const line of chunk.toString("utf8").split(/\r?\n/)) {
          const text = parseClaudeStreamLine(line);
          if (!text) {
            continue;
          }
          output += text;
          context.emit({
            type: "text_delta",
            runId: context.run.id,
            conversationId: context.run.conversationId,
            agentId: context.run.agentId,
            payload: { text }
          });
        }
      });

      child.stderr.on("data", (chunk: Buffer) => {
        stderr += chunk.toString("utf8");
      });

      child.on("error", async (error) => {
        if (settled) {
          return;
        }
        settled = true;
        this.children.delete(context.run.id);
        const message = error instanceof Error ? error.message : String(error);
        const failure = `Spawn failed: ${message}`;
        await writeFile(context.worktree.logPath, `${evidenceLog}${output}\n${stderr}${failure}\n`, "utf8");
        reject(new Error(`Failed to spawn agent command "${command}": ${message}`));
      });
      child.on("close", async (code) => {
        if (settled) {
          return;
        }
        settled = true;
        this.children.delete(context.run.id);
        if (code !== 0) {
          const failure = stderr || `Agent command exited with code ${code}`;
          await writeFile(context.worktree.logPath, `${evidenceLog}${output}\n${stderr}Failure: ${failure}\n`, "utf8");
          reject(new Error(failure));
          return;
        }
        await writeFile(context.worktree.logPath, `${evidenceLog}${output}\n${stderr}`, "utf8");
        resolve({
          output,
          summary: `# AgentHub Run ${context.run.id}\n\n${output || "Claude completed without text output."}\n`
        });
      });

      child.stdin.end(wrappedPrompt);
    });
  }
}
