import { Injectable } from "@nestjs/common";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentEvent, AgentRun } from "@agenthub/shared";
import type { PreparedWorktree } from "./worktree.service";

export interface RunnerContext {
  run: AgentRun;
  prompt: string;
  worktree: PreparedWorktree;
  emit: (event: Omit<AgentEvent, "eventId" | "seq" | "ts">) => void;
}

export interface RunnerResult {
  output: string;
  summary: string;
}

export function parseClaudeStreamLine(line: string): string | undefined {
  const trimmed = line.trim();
  if (!trimmed) {
    return undefined;
  }

  try {
    const parsed = JSON.parse(trimmed) as {
      type?: string;
      text?: string;
      content?: Array<{ type?: string; text?: string }>;
      delta?: { text?: string };
    };
    if (typeof parsed.text === "string") {
      return parsed.text;
    }
    if (typeof parsed.delta?.text === "string") {
      return parsed.delta.text;
    }
    const textPart = parsed.content?.find((part) => part.type === "text" && typeof part.text === "string");
    return textPart?.text;
  } catch {
    return trimmed;
  }

  return undefined;
}

@Injectable()
export class AgentRunner {
  private readonly children = new Map<string, ChildProcessWithoutNullStreams>();

  async run(context: RunnerContext): Promise<RunnerResult> {
    if (process.env.MOCK_AGENT === "true") {
      return this.runMock(context);
    }
    return this.runClaude(context);
  }

  cancel(runId: string): boolean {
    const child = this.children.get(runId);
    if (!child) {
      return false;
    }
    child.kill("SIGTERM");
    this.children.delete(runId);
    return true;
  }

  private async runMock(context: RunnerContext): Promise<RunnerResult> {
    context.emit({
      type: "agent_thinking",
      runId: context.run.id,
      conversationId: context.run.conversationId,
      agentId: context.run.agentId,
      payload: { mode: "mock" }
    });

    const backendDir = join(context.worktree.worktreePath, "backend", "src", "generated");
    const frontendDir = join(context.worktree.worktreePath, "frontend", "src", "generated");
    await mkdir(backendDir, { recursive: true });
    await mkdir(frontendDir, { recursive: true });

    await writeFile(
      join(backendDir, "todo-service.ts"),
      [
        "export interface TodoItem {",
        "  id: string;",
        "  title: string;",
        "  done: boolean;",
        "}",
        "",
        "export function createTodo(title: string): TodoItem {",
        "  return { id: crypto.randomUUID(), title, done: false };",
        "}",
        ""
      ].join("\n"),
      "utf8"
    );
    await writeFile(
      join(frontendDir, "TodoList.tsx"),
      [
        "export function TodoList() {",
        "  return <section><h2>Mock Todo List</h2><p>Generated by AgentHub MOCK_AGENT.</p></section>;",
        "}",
        ""
      ].join("\n"),
      "utf8"
    );

    const output = `MOCK_AGENT generated todo examples for prompt: ${context.prompt}`;
    await writeFile(context.worktree.logPath, `${output}\n`, "utf8");
    context.emit({
      type: "text_delta",
      runId: context.run.id,
      conversationId: context.run.conversationId,
      agentId: context.run.agentId,
      payload: { text: output }
    });

    return {
      output,
      summary: `# AgentHub Run ${context.run.id}\n\n${output}\n`
    };
  }

  private async runClaude(context: RunnerContext): Promise<RunnerResult> {
    const command = process.env.AGENT_COMMAND ?? "claude";
    const args = ["--print", "--output-format", "stream-json", "--dangerously-skip-permissions"];
    const evidence = {
      mode: "claude-cli",
      command,
      cwd: context.worktree.worktreePath
    };
    const evidenceLog = `Agent execution mode: ${JSON.stringify(evidence)}\n`;

    context.emit({
      type: "agent_thinking",
      runId: context.run.id,
      conversationId: context.run.conversationId,
      agentId: context.run.agentId,
      payload: evidence
    });
    await writeFile(context.worktree.logPath, evidenceLog, "utf8");

    return new Promise((resolve, reject) => {
      let child: ChildProcessWithoutNullStreams;
      try {
        child = spawn(command, args, {
          cwd: context.worktree.worktreePath,
          env: process.env
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        void writeFile(context.worktree.logPath, `${evidenceLog}Spawn failed: ${message}\n`, "utf8");
        reject(new Error(`Failed to spawn agent command "${command}": ${message}`));
        return;
      }
      this.children.set(context.run.id, child);
      let output = "";
      let stderr = "";
      let settled = false;

      child.stdout.on("data", (chunk: Buffer) => {
        for (const line of chunk.toString("utf8").split(/\r?\n/)) {
          const text = parseClaudeStreamLine(line);
          if (!text) {
            continue;
          }
          output += text;
          context.emit({
            type: "text_delta",
            runId: context.run.id,
            conversationId: context.run.conversationId,
            agentId: context.run.agentId,
            payload: { text }
          });
        }
      });

      child.stderr.on("data", (chunk: Buffer) => {
        stderr += chunk.toString("utf8");
      });

      child.on("error", async (error) => {
        if (settled) {
          return;
        }
        settled = true;
        this.children.delete(context.run.id);
        const message = error instanceof Error ? error.message : String(error);
        const failure = `Spawn failed: ${message}`;
        await writeFile(context.worktree.logPath, `${evidenceLog}${output}\n${stderr}${failure}\n`, "utf8");
        reject(new Error(`Failed to spawn agent command "${command}": ${message}`));
      });
      child.on("close", async (code) => {
        if (settled) {
          return;
        }
        settled = true;
        this.children.delete(context.run.id);
        if (code !== 0) {
          const failure = stderr || `Agent command exited with code ${code}`;
          await writeFile(context.worktree.logPath, `${evidenceLog}${output}\n${stderr}Failure: ${failure}\n`, "utf8");
          reject(new Error(failure));
          return;
        }
        await writeFile(context.worktree.logPath, `${evidenceLog}${output}\n${stderr}`, "utf8");
        resolve({
          output,
          summary: `# AgentHub Run ${context.run.id}\n\n${output || "Claude completed without text output."}\n`
        });
      });

      child.stdin.end(context.prompt);
    });
  }
}
